# Generated by Django 5.2 on 2025-04-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analisis', '0001_initial'),
        ('scraping', '0002_habilidad_alter_ofertaempleo_habilidades'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Habilidad',
        ),
        migrations.AlterField(
            model_name='ofertaempleo',
            name='habilidades',
            field=models.ManyToManyField(related_name='ofertas', to='analisis.habilidad'),
        ),
    ]
