# Generated by Django 5.2 on 2025-04-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_delete_habilidad_alter_ofertaempleo_habilidades'),
    ]

    operations = [
        migrations.AddField(
            model_name='ofertaempleo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ofertaempleo',
            name='tecnologias',
            field=models.TextField(blank=True, null=True),
        ),
    ]
