# Generated by Django 5.2 on 2025-04-10 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('analisis', '0001_initial'),
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrediccionHabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prediccion', models.DateField()),
                ('valor_estimado', models.FloatField(help_text='Popularidad estimada')),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('habilidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analisis.habilidad')),
            ],
        ),
        migrations.CreateModel(
            name='RecomendacionTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.FloatField(help_text='Puntaje de recomendación')),
                ('generado_en', models.DateTimeField(auto_now_add=True)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyectos.tarea')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'tarea')},
            },
        ),
    ]
